#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

args="$0 $*"
echo "args: \033[1;37m$(($# + 1))\033[0;37m, [ \033[0;35m$args\033[0;37m ]" >&2

start=$1
end=$2
skip=$3
step=$(echo "scale=15; ($end - $start) / 1501;" | /usr/bin/bc)
shift 3
datalines=$5
command=$*

tmpdir=${TMP_TAYLOR:-/tmp/$USER}
tmpfile=${tmpdir}/data
filtered=${tmpdir}/bifurcation
for tag in X x Y y Z z
do
    >${filtered}${tag}
done

[ $skip -eq 0 ] && lower=1 || lower=$((datalines / skip + 1))
upper=$((datalines + 1))

col='[^ ]*'
space=' *'

filter () {  # $1 is the turning point tag, $2 is the column containing its data
    /bin/grep $1 ${tmpfile} | /bin/sed --expression="s/\($col\)$space\($col\)$space\($col\) *.*/$p \\$2/" >>${filtered}$1 &
}

p=${start}
while [ $(echo "$p < $end" | /usr/bin/bc) -eq 1 ]
do
    eval ${command} 2>/dev/null | /bin/sed --quiet "$lower,$ p" >${tmpfile}  # run & save data, skipping "transient"
    echo -n "." >&2
    if [ $(/usr/bin/wc --lines <$tmpfile) -eq $((upper - lower + 1)) ]
    then
        echo "   Processing parameter value: $p"
        filter 'X' 1
        filter 'x' 1
        filter 'Y' 2
        filter 'y' 2
        filter 'Z' 3
        filter 'z' 3
        wait
    else
        echo "UNBOUNDED for parameter value: $p"
    fi
    p=$(echo "$p + $step;" | /usr/bin/bc)
done
echo "" >&2

base='set terminal png size 1350,800 background rgb "grey85"; set grid back;'
/usr/bin/gnuplot -e "set title '$args'; $base plot '${filtered}X' lt rgb '#000080' w dots, '${filtered}x' lt rgb '#004040' w dots" \
    >${tmpdir}/X.png &
/usr/bin/gnuplot -e "set title '$args'; $base plot '${filtered}Y' lt rgb '#008000' w dots, '${filtered}y' lt rgb '#404000' w dots" \
    >${tmpdir}/Y.png &
/usr/bin/gnuplot -e "set title '$args'; $base plot '${filtered}Z' lt rgb '#800000' w dots, '${filtered}z' lt rgb '#400040' w dots" \
    >${tmpdir}/Z.png &
wait

/usr/bin/display ${tmpdir}/X.png &
/usr/bin/display ${tmpdir}/Y.png &
/usr/bin/display ${tmpdir}/Z.png &
