#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

args="$0 $*"
echo "args: \033[1;37m$(($# + 1))\033[0;37m, [ \033[0;35m$args\033[0;37m ]" >&2

start=$1
end=$2
steps=1000
increment=$(echo "scale=12; ($end - $start) / $steps;" | /usr/bin/bc)
skip=$3
shift 3
datalines=$5
command=$*

tmpdir=${TMP_TAYLOR:-/tmp/$USER}
tmpfile=${tmpdir}/data
filtered=${tmpdir}/bifurcation
for tag in X x Y y Z z
do
    >${filtered}$tag
done

lower=1
[ $skip -ne 0 ] && lower=$((datalines / skip + 1))
upper=$((datalines + 1))

filter () {  # $1 is the turning point tag, $2 is the column containing its data
    data='[^ ][^ ]*'
    /bin/grep $1 $tmpfile | /bin/sed "s/\($data\) \($data\) \($data\) .*/$p \\$2/" >>${filtered}$1 &
}

p=$start
count=$steps
while [ $count -ge 0 ]
do
    eval $command 2>/dev/null | /bin/sed --quiet "$lower,$ p" >$tmpfile  # run & save data, skipping "transient"
    if [ $(/usr/bin/wc --lines <$tmpfile) -eq $((upper - lower + 1)) ]
    then
        echo -n "\r   \033[0;32mProcessing value\033[0;37m $p"
        filter 'X' 1
        filter 'x' 1
        filter 'Y' 2
        filter 'y' 2
        filter 'Z' 3
        filter 'z' 3
        wait
    else
        echo -n "\r   \033[1;31mProcessing value\033[0;37m $p"
    fi
    p=$(echo "$p + $increment;" | /usr/bin/bc)
    count=$((count - 1))
done
echo -n "\r                                                            \r"

xmargin=50
pwidth=$((steps + 1 + 2 * xmargin))

plot () {
/usr/bin/gnuplot -p << EOF
set terminal png size '$pwidth',640 background rgb "grey85"
set lmargin at screen '$xmargin.0'/'$pwidth'
set rmargin at screen '$((xmargin + steps)).0'/'$pwidth'
set grid back
set border back
set title '$args'
set format x "%.6g"
plot '${filtered}$1' lt rgb '$2' w dots, '${filtered}$3' lt rgb '$4' w dots
EOF
}

plot X '#000080' x '#004040' >${tmpdir}/X.png &
plot Y '#008000' y '#404000' >${tmpdir}/Y.png &
plot Z '#800000' z '#400040' >${tmpdir}/Z.png &
wait

/usr/bin/display ${tmpdir}/X.png &
/usr/bin/display ${tmpdir}/Y.png &
/usr/bin/display ${tmpdir}/Z.png &
