#!/bin/sh

#choice=$(yad --columns=2 --title="Black Hole Playground" --form --separator=" " --align=right \
#    --field="Geodesic Type":CB --field="Output Type":CB \
#    -- '^Time-like!Light-like' \
#       '^GLplot!Gnuplot3D!Gnuplot2D')

#set $choice
#geodesic=$1
#output=$2

./h-kerr-gl $(yad --columns=2 --title="Kerr Orbit" --form --separator=" " --align=right \
    --field="Display Mode":CB --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM --field="Track Length":NUM \
    --field="BH spin":NUM --field="particle mass":CB \
    --field="particle energy" --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
    --field="r0" --field="theta0" \
    -- '0!1!2' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' '1000!1..100000!1' \
       "0.8!-1.0..1.0!0.1!1" "^1.0!0.0" \
       "0.9455050956749083" "1.434374509531738" "1.0" "7.978759958927879" \
       "12.0" "63.0")

