#!/bin/sh

user_dir="/tmp/$USER"
[ ! -d $user_dir ] && mkdir $user_dir
user_data="$user_dir/data"

choice=$(yad --columns=2 --title="Black Hole Playground" --form --separator=" " --align=right \
    --field="Geodesic Type":CB --field="Output Type":CB \
    -- '^Timelike!Lightlike' \
       '^GLplot!Geodesic!Errors!Speed')

case $? in
    1) exit;;
esac

set $choice
type=$1
analysis=$2

plot3d () {
gnuplot -p << EOF
set terminal wxt size 600,450
set xlabel 'X'
set ylabel 'Y'
set zlabel 'Z'
splot '$user_data' with lines
EOF
}

plot_errors () {
gnuplot -p << EOF
set key left
set terminal wxt size 600,450
set yrange [24:0]
set xlabel 'Mino time'
set ylabel 'approximate places'
plot '$user_data' using 4:5 title 'v4' with lines, '' u 4:6 t 'r' w l, '' u 4:7 t 'theta' w l
EOF
gnuplot -p << EOF
set key left
set terminal wxt size 600,450
set yrange [24:0]
set xlabel 'Proper time'
set ylabel 'approximate places'
plot '$user_data' using 10:5 title 'v4' with lines, '' u 10:6 t 'r' w l, '' u 10:7 t 'theta' w l
EOF
gnuplot -p << EOF
set key left
set terminal wxt size 600,450
set yrange [24:0]
set xlabel 'Coordinate time'
set ylabel 'approximate places'
plot '$user_data' using 11:5 title 'v4' with lines, '' u 11:6 t 'r' w l, '' u 11:7 t 'theta' w l
EOF
}

plot_speed () {
gnuplot -p << EOF
set key left
set terminal wxt size 600,450
set xlabel 'Mino time'
set ylabel 'gamma \& speed'
plot '$user_data' using 4:8 title 'gamma' with lines, '' u 4:9 t 'speed' w l
EOF
gnuplot -p << EOF
set key left
set terminal wxt size 600,450
set xlabel 'Proper time'
set ylabel 'gamma \& speed'
plot '$user_data' using 10:8 title 'gamma' with lines, '' u 10:9 t 'speed' w l
EOF
gnuplot -p << EOF
set key left
set terminal wxt size 600,450
set xlabel 'Coordinate time'
set ylabel 'gamma \& speed'
plot '$user_data' using 11:8 title 'gamma' with lines, '' u 11:9 t 'speed' w l
EOF
}

case $type in
    Timelike)
        case $analysis in
            GLplot) ./h-kerr-gl _ \
                $(yad --columns=2 --title="Kerr Particle Orbit GL" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM --field="Track Length":NUM \
                --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy" --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' '2000!1..100000!1' \
                   "0.8!-1.0..1.0!0.1!1" "1.0" \
                   "0.9455050956749083" "1.434374509531738" "1.0" "7.978759958927879" \
                   "12.0" "63.0")
            ;;
            Geodesic|Errors|Speed) ./h-kerr-std \
                $(yad --columns=2 --title="Kerr Particle Orbit Gnuplot" --form --separator=" " --align=right \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="Plot type":CB --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy" --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '6!0..36!3' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' \
                   '0!1!2' "0.8!-1.0..1.0!0.1!1" "1.0" \
                   "0.9455050956749083" "1.434374509531738" "1.0" "7.978759958927879" \
                   "12.0" "63.0") >$user_data
                case $analysis in
                    Geodesic) plot3d;;
                    Errors) plot_errors;;
                    Speed) plot_speed;;
                esac
            ;;
        esac
    ;;
    Lightlike)
        case $analysis in
            GLplot) ./h-kerr-gl _ \
                $(yad --columns=2 --title="Kerr Light Orbit GL" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM --field="Track Length":NUM \
                --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy":RO --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' '2000!1..100000!1' \
                   "0.8!-1.0..1.0!0.1!1" "0.0" \
                   "1.0" "-1.6" "1.0" "27.0" \
                   "3.0" "0.0")
            ;;
            Geodesic|Errors|Speed) ./h-kerr-std \
                $(yad --columns=2 --title="Kerr Light Orbit Gnuplot" --form --separator=" " --align=right \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="Plot type":CB --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy":RO --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '6!0..36!3' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' \
                   '0!1!2' "0.8!-1.0..1.0!0.1!1" "0.0" \
                   "1.0" "-1.6" "1.0" "27.0" \
                   "3.0" "0.0") >$user_data
                case $analysis in
                    Geodesic) plot3d;;
                    Errors) plot_errors;;
                    Speed) plot_speed;;
                esac
            ;;
        esac
    ;;
esac
