#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

choice=$(yad --columns=2 --title="Black Hole Playground" --form --separator=" " --align=right \
    --field="Geodesic Type":CB --field="Output Type":CB --field="Time Variable":CB \
    -- '^Timelike!Lightlike' '^GLplot!Gnuplot' '^Mino!Proper!Coordinate')

case $? in
    1) exit;;
esac

set $choice
type=$1
analysis=$2
time=$3

plot () {
/usr/bin/gnuplot << EOF
set key left
set terminal qt size 600,450
set yrange [24:0]
set xlabel "$2"
set ylabel 'approximate places'
plot '$user_data' using $1:5 title 'v4' with lines, '' u $1:6 t 'r' w l, '' u $1:7 t 'theta' w l
pause mouse close
EOF
/usr/bin/gnuplot << EOF
set key left
set terminal qt size 600,450
set xlabel "$2"
set ylabel 'gamma \& speed'
plot '$user_data' using $1:8 title 'gamma' with lines, '' u $1:9 t 'speed' w l
pause mouse close
EOF
}

case $analysis in
    GLplot)
        case $type in
            Timelike)
                ./h-kerr-gl $(yad --columns=2 --title="Kerr Particle Orbit GL" --form --separator=" " --align=right \
                --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy" --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '2000!1000..10000!1000' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' \
                   "0.8!-1.0..1.0!0.1!1" "1.0" \
                   "0.9455050956749083" "1.434374509531738" "1.0" "7.978759958927879" \
                   "12.0" "63.0") ;;
            Lightlike)
                ./h-kerr-gl $(yad --columns=2 --title="Kerr Light Orbit GL" --form --separator=" " --align=right \
                --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy":RO --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '2000!1000..10000!1000' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' \
                   "0.8!-1.0..1.0!0.1!1" "0.0" \
                   "1.0" "-1.6" "1.0" "27.0" \
                   "3.0" "0.0") ;;
        esac ;;
    Gnuplot)
        case $type in
            Timelike)
                ./plot 10000 ./h-kerr-std $(yad --columns=2 --title="Kerr Particle Orbit Gnuplot" --form --separator=" " --align=right \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy" --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '6!0..36!3' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' \
                   "0.8!-1.0..1.0!0.1!1" "1.0" \
                   "0.9455050956749083" "1.434374509531738" "1.0" "7.978759958927879" \
                   "12.0" "63.0") ;;
            Lightlike)
                ./plot 10000 ./h-kerr-std $(yad --columns=2 --title="Kerr Light Orbit Gnuplot" --form --separator=" " --align=right \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="BH spin":NUM --field="particle mass":RO \
                --field="particle energy":RO --field="particle momentum" --field="momentum factor" --field="Carter's constant" \
                --field="r0" --field="theta0" \
                -- '6!0..36!3' '4!2..10!2' '0.01!0.001..1!0.001!3' '10000!1..100000!1' \
                   "0.8!-1.0..1.0!0.1!1" "0.0" \
                   "1.0" "-1.6" "1.0" "27.0" \
                   "3.0" "0.0") ;;
        esac
        case $time in
            Mino) plot 4 'Mino Time';;
            Proper) plot 10 'Proper Time';;
            Coordinate) plot 11 'Coordinate Time';;
        esac ;;
esac
