#!/bin/sh
#
#  (c) 2018-2020 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#
#  Example: time -p ./build gcc && echo OK

WARNINGS='-pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wextra'

CC='/usr/bin/musl-gcc -std=c99'
if [ x"$1" = x'clang' ]
then
    CC='/usr/bin/clang'
elif [ x"$1" = x'gcc' ]
then
    CC='/usr/bin/c99'
fi
${CC} --version

rm -f *.o *.so *.gch

build () {
    name=$1
    ${CC} -O3 -DNDEBUG -static -o ${name}-static ${name}.c taylor-ode.c -lm -s
    ${CC} -O0 $WARNINGS -g -o ${name}-dbg ${name}.c taylor-ode.c -lm
}

for model in \
tsm-bouali \
tsm-halvorsen \
tsm-lorenz \
tsm-rossler \
tsm-genesio-tesi \
tsm-rucklidge \
tsm-rf \
tsm-thomas \
tsm-sj \
tsm-sprott-minimal \
tsm-sprott-thomas \
tsm-wimol-banlue \
tsm-yu-wang
do
    rm -f ${model}-*
    build ${model} &
done

echo " Building libODE"
rm -f libtaylor.so taylor-ode.o
${CC} -O3 -DNDEBUG -c $WARNINGS -fpic taylor-ode.c && ${CC} -shared -o libode.so taylor-ode.o -s &
# Example:
# gcc -O3 -DNDEBUG -L. -Wall -o test tsm-lorenz.c -lode -lm -s
# LD_LIBRARY_PATH=. ./test 15 _ 10 .01 10000 -15.8 -17.48 35.64 10 28 8 3 | gnuplot -p -e "splot '<cat' with lines"

wait
ls -lh --color tsm-* lib*.so
