#!/bin/sh

# Copyright (c) 2018-2020, Ian Smith (m4r35n357)
# All rights reserved.
# For licencing see LICENCE file

WARNINGS='-pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wextra'

CC='/usr/bin/c99'
if [ x"$1" = x'clang' ]
then
    CC='/usr/bin/clang'
fi

build () {
    name=$1
    ${CC} -O3 -DNDEBUG -o ${name} ${name}.c taylor-ode.c -lmpfr -s
    ${CC} -O3 -DNDEBUG -static -o ${name}-static ${name}.c taylor-ode.c -lmpfr -lgmp -s
    ${CC} -Og $WARNINGS -g -o ${name}-dbg ${name}.c taylor-ode.c -lmpfr
}

for model in \
tsm-double-pendulum \
tsm-lorenz \
tsm-rossler \
tsm-yu-wang \
tsm-genesio-tesi \
tsm-rucklidge \
tsm-halvorsen \
tsm-bouali \
tsm-rf \
tsm-wimol-banlue \
tsm-thomas \
tsm-sprott-minimal \
tsm-sprott-thomas \
tsm-sj \
tsm-lotka-volterra \
tsm-logistic \
tsm-constant
do
    build ${model} &
done

${CC} -Og -Wall -g -o ad-test-dbg taylor-ode.c ad.c ad-test.c -lmpfr &
${CC} -Og -Wall -g -o ad-test-newton-dbg taylor-ode.c ad.c ad-test-newton.c -lmpfr &

wait
ls -lh --color ad-test* tsm-*

