#!/bin/sh

/usr/bin/ctags *.c

WARNINGS='-pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wextra -Wconversion'
STD='c99'

CC="/usr/bin/gcc -std=$STD"
if [ x"$1" = x'clang' ]
then
    CC="/usr/bin/clang -std=$STD"
elif [ x"$1" = x'gcc' ]
then
    CC="/usr/bin/gcc -std=$STD"
fi
${CC} --version

rm -f *.o *.so *.gch

build () {
    name=$1
    echo " Building $name"
    ${CC} -O3 -DNDEBUG -o ${name}-dynamic ${name}.c taylor-ode.c main.c -lmpfr -s
    ${CC} -O3 -DNDEBUG -static -o ${name}-static ${name}.c taylor-ode.c main.c -lmpfr -lgmp -s
    ${CC} -O0 $WARNINGS -g -o ${name}-dbg ${name}.c taylor-ode.c main.c -lmpfr
}

for model in \
tsm-halvorsen \
tsm-lorenz \
tsm-thomas
do
    rm -f ${model}-*
    build ${model} &
done

wait

echo ""
ls -lh --color *ad-* tsm-* rk4-*
