#!/bin/sh

#  Example: time -p ./chaos-scan ode min max 2>/dev/null | tee /tmp/results

ode=$1
shift
start=$1
end=$2
step=$(echo "scale=12; ($end - $start) / 201;" | bc)
timestep=${3:-.1}
datalines=${4:-10000}
lower=${5:-0.01}
upper=${6:-0.1}
order=${7:-10}

case $ode in
    'thomas')       cmd='./tsm-thomas-static 15 _ $order $timestep $datalines  1 0 0  $x';;
    'lorenz')       cmd='./tsm-lorenz-static 15 _ $order $timestep $datalines  -15.8 -17.48 35.64  10 $x 8 3';;
    'rossler')      cmd='./tsm-rossler-static 15 _ $order $timestep $datalines  .0 -6.78 .02  .1 .1 $x';;
    'sprott')       cmd='./tsm-sprott-minimal-static 15 _ $order $timestep $datalines  .02 0 0  $x';;
    'halvorsen')    cmd='./tsm-halvorsen-static 15 _ $order $timestep $datalines  1 0 0  $x 4';;
    'rucklidge')    cmd='./tsm-rucklidge-static 15 _ $order $timestep $datalines  1 0 0  $x 2';;
    'rf')           cmd='./tsm-rf-static 15 _ $order $timestep $datalines  .05 -.05 .3  $x .1';;
    'bouali')       cmd='./tsm-bouali-static 15 _ $order $timestep $datalines  1 1 0  3 2.2 1 $x';;
    'gt')           cmd='./tsm-genesio-tesi-static 15 _ $order $timestep $datalines  .1 .1 .1  $x 1.1 1';;
    'wb')           cmd='./tsm-wimol-banlue-static 15 _ $order $timestep $datalines  1 0 0  $x';;
    'yw')           cmd='./tsm-yu-wang-static 15 _ $order $timestep $datalines  1 0 0  10 40 2 $x';;
    'minimal')      cmd='./tsm-sprott-minimal-static 15 _ $order $timestep $datalines  .02 0 0  $x';;
    *)              echo "Unknown ODE"; exit;;
esac

x=$start
while [ 1 -eq $(echo "$x < $end" | bc) ]
do
    echo -n "$x "
    eval ./cns both noplot "$cmd" >/dev/null 2>/dev/null
    ./chaos-distance-cns.py $((datalines + 1)) $lower $upper
    x=$(echo "$x + $step;" | bc)
done

