#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

args="$0 $*"
echo "args: \033[1;37m$(($# + 1))\033[0;37m, [ \033[0;35m$args\033[0;37m ]" >&2

start=$1
end=$2
steps=1000
increment=$(echo "scale=9; ($end - $start) / $steps;" | /usr/bin/bc)
samples=$3
shift 3
datalines=$5
command=$*

tmpdir=${TMP_TAYLOR:-/tmp/$USER}
tmp_raw=${tmpdir}/data
tmp_valid=${tmpdir}/samples
filtered=${tmpdir}/chaos
for tag in X x Y y Z z
do
    >${filtered}$tag
done

filter () {  # $1 is the turning point tag, $2 is the column containing its data
    data='[^ ][^ ]*'
    /bin/grep $1 $tmp_valid | /bin/sed "s/\($data\) \($data\) \($data\) .*/$p \\$2/" >>${filtered}$1 &
}

p=$start
count=$steps
while [ $count -ge 0 ]
do
    eval $command 2>/dev/null | /usr/bin/tee $tmp_raw | /usr/bin/tail -n $samples >$tmp_valid
    if [ $(/usr/bin/wc --lines <$tmp_raw) -eq $((datalines + 1)) ]
    then
        echo -n "\r   \033[0;32mLatest value\033[0;37m $p"
        filter 'X' 1
        filter 'x' 1
        filter 'Y' 2
        filter 'y' 2
        filter 'Z' 3
        filter 'z' 3
        wait
    else
        echo -n "\r   \033[1;31mLatest value\033[0;37m $p"
    fi
    p=$(echo "$p + $increment;" | /usr/bin/bc)
    count=$((count - 1))
done
echo -n "\r                                                            \r"

xmargin=50
pwidth=$((steps + 2 * xmargin))

plot () {
/usr/bin/gnuplot -p << EOF
set terminal $5 size '$pwidth',640 background rgb "grey85"
set lmargin at screen '$xmargin.0'/'$pwidth'
set rmargin at screen '$((xmargin + steps)).0'/'$pwidth'
set grid back
set border back
set title '$args'
set xrange [$start:$end]
set format x "%.6g"
plot 1/0 lt rgb '$2' lw 3 t 'Maxima', '${filtered}$1' lt rgb '$2' notitle w dots,\
     1/0 lt rgb '$4' lw 3 t 'Minima', '${filtered}$3' lt rgb '$4' notitle w dots
EOF
}

plot X '#000080' x '#004040' png >${tmpdir}/X.png &
plot Y '#008000' y '#404000' png >${tmpdir}/Y.png &
plot Z '#800000' z '#400040' png >${tmpdir}/Z.png &
wait

plot X '#000080' x '#004040' wxt &
plot Y '#008000' y '#404000' wxt &
plot Z '#800000' z '#400040' wxt &
