#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

args="$0 $*"
echo "args: \033[1;37m$(($# + 1))\033[0;37m, [ \033[0;35m$args\033[0;37m ]" >&2

start=$1
end=$2
steps=1000
increment=$(echo "scale=9; ($end - $start) / $steps;" | /usr/bin/bc)
samples=$3
shift 3
datalines=$(($5 + 1))
command=$*

tmpdir=${TMP_TAYLOR:-/tmp/$USER}
tmp_raw=${tmpdir}/data
tmp_valid=${tmpdir}/samples
filtered=${tmpdir}/chaos
for tag in X x Y y Z z
do
    >${filtered}$tag
done
snaps=$tmpdir/snapshots
[ ! -d $snaps ] && mkdir -p $snaps
rm -f $snaps/*.png

filter () {  # $1 is the turning point tag, $2 is the column containing its data
    data='[^ ][^ ]*'
    /bin/grep $1 $tmp_valid | /bin/sed "s/\($data\) \($data\) \($data\) .*/$p \\$2/" >>${filtered}$1
}

snapshot () {
/usr/bin/gnuplot << EOF
set terminal pngcairo size 1024,768
set title '$args'
set xyplane 0
set view 54.73561,$(echo "scale=6; 360 * $1 / $2;" | /usr/bin/bc -l)
set xlabel 'X'
set ylabel 'Y'
set zlabel 'Z'
splot '$tmp_valid' with lines
EOF
}

p=$(echo "scale=9; $start / 1.0;" | /usr/bin/bc)
count=$steps
while [ $count -ge 0 ]
do
    percent=$(((steps - count) / 10))
    eval $command 2>/dev/null | /usr/bin/tee $tmp_raw | /usr/bin/tail -n $samples >$tmp_valid
    snapshot $count $steps >$snaps/snap_$p.png &
    if [ $(/usr/bin/wc --lines <$tmp_raw) -eq $datalines ]
    then
        echo -n "\r\033[1;37m $percent\033[0;37m%  \033[0;32mLatest value\033[0;37m $p"
        filter 'X' 1 &
        filter 'x' 1 &
        filter 'Y' 2 &
        filter 'y' 2 &
        filter 'Z' 3 &
        filter 'z' 3 &
    else
        echo -n "\r\033[1;37m $percent\033[0;37m%  \033[1;31mLatest value\033[0;37m $p"
    fi
    wait
    p=$(echo "$p + $increment;" | /usr/bin/bc)
    count=$((count - 1))
done
echo -n "\r                                                            \r"

xmargin=50
pwidth=$((steps + 2 * xmargin))

plot () {
/usr/bin/gnuplot << EOF
set terminal $5 size '$pwidth',640
set lmargin at screen '$xmargin.0'/'$pwidth'
set rmargin at screen '$((xmargin + steps)).0'/'$pwidth'
set grid back
set border back
set title '$args'
set xrange [$start:$end]
set format x "%.6g"
plot 1/0 lt rgb '$2' lw 3 t '$1 maxima', '${filtered}$1' lt rgb '$2' notitle w dots,\
     1/0 lt rgb '$4' lw 3 t '$1 minima', '${filtered}$3' lt rgb '$4' notitle w dots
if (GNUTERM eq 'qt') pause mouse close
EOF
}

plot X '#000080' x '#004040' png >${tmpdir}/X.png &
plot Y '#008000' y '#404000' png >${tmpdir}/Y.png &
plot Z '#800000' z '#400040' png >${tmpdir}/Z.png &
wait

plot X '#000080' x '#004040' qt &
plot Y '#008000' y '#404000' qt &
plot Z '#800000' z '#400040' qt &
