#!/bin/sh

#  Example: time -p ./chaos-scan ode method min max 2>/dev/null | tee /tmp/results

ode=$1
method=$2
case $method in
    'tsm')       prog='tsm'; param='12';;
    'rk4')       prog='rk4'; param='1';;
    *)           echo "Unknown method"; exit;;
esac
shift 2
start=$1
end=$2
step=$(echo "scale=12; ($end - $start) / 201;" | bc)
timestep=${3:-0.1}
datalines=${4:-10000}
separation1=${5:-0.000001}
ratio=${6:-10}
separation2=$(echo "scale=15; $separation1 / $ratio;" | bc)

case $ode in
    'thomas')       cmd='./$prog-thomas-static 15 NA $param $timestep $datalines 1 0 0  $x';;
    'lorenz')       cmd='./$prog-lorenz-static 15 NA $param $timestep $datalines -15.8 -17.48 35.64  10 $x 8 3';;
    'rossler')      cmd='./$prog-rossler-static 15 NA $param $timestep $datalines 0.0 -6.78 0.02  0.1 0.1 $x';;
    'sprott')       cmd='./$prog-sprott-minimal-static 15 NA $param $timestep $datalines .02 0 0  $x';;
    'halvorsen')    cmd='./$prog-halvorsen-static 15 NA $param $timestep $datalines 1 0 0  $x';;
    'rucklidge')    cmd='./$prog-rucklidge-static 15 NA $param $timestep $datalines 1 0 0  $x 2';;
    'rf')           cmd='./$prog-rf-static 15 NA $param $timestep $datalines .05 -.05 .3  $x .1';;
    'bouali')       cmd='./$prog-bouali-static 15 NA $param $timestep $datalines 1 1 0  3 2.2 1 $x';;
    'gt')           cmd='./$prog-genesio-tesi-static 15 NA $param $timestep $datalines .1 .1 .1  $x 1.1 1';;
    'wb')           cmd='./$prog-wimol-banlue-static 15 NA $param $timestep $datalines 1 0 0  $x';;
    'yw')           cmd='./$prog-yu-wang-static 15 NA $param $timestep $datalines 1 0 0  10 40 2 $x';;
    'minimal')      cmd='./$prog-sprott-minimal-static 15 NA $param $timestep $datalines .02 0 0  $x';;
    *)              echo "Unknown ODE"; exit;;
esac

x=$start
while [ 1 -eq "$(echo "$x < $end" | bc)" ]
do
    echo -n "$x "
    eval ./ic "$separation1" noplot "$cmd" >/dev/null 2>/dev/null
    mv /tmp/dataA /tmp/data1
    mv /tmp/dataB /tmp/data2
    mv /tmp/dataC /tmp/data3
    mv /tmp/dataD /tmp/data4
    mv /tmp/dataE /tmp/data5
    mv /tmp/dataF /tmp/data6
    mv /tmp/dataG /tmp/data7
    eval ./ic "$separation2" noplot "$cmd" >/dev/null 2>/dev/null
    ./chaos-distance.py $((datalines + 1)) "$separation1" "$separation2"
    x=$(echo "$x + $step;" | bc)
done

