#!/bin/sh
#
#  (c) 2018-2020 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#
#  Example: ./chaos-scan-cns thomas .01 .21 .1 10000 .000000001 .01 10 16
#

echo "Predictability vs Parameter Value: [$*]" >&2

ode=$1
shift
start=$1
end=$2
step=$(echo "scale=15; ($end - $start) / 201;" | bc)
timestep=${3:-.1}
datalines=${4:-10000}
lower=${5:-0.000000001}
upper=${6:-0.01}
order=${7:-10}
dp=${8:-16}

case $ode in
    'thomas')       cmd='./tsm-thomas-static $dp _ $order $timestep $datalines  1 0 0  $p';;
    'lorenz')       cmd='./tsm-lorenz-static $dp _ $order $timestep $datalines  -15.8 -17.48 35.64  10 $p 8 3';;
    'rossler')      cmd='./tsm-rossler-static $dp _ $order $timestep $datalines  .0 -6.78 .02  .1 .1 $p';;
    'sprott')       cmd='./tsm-sprott-minimal-static $dp _ $order $timestep $datalines  .02 0 0  $p';;
    'halvorsen')    cmd='./tsm-halvorsen-static $dp _ $order $timestep $datalines  1 0 0  $p 4';;
    'rucklidge')    cmd='./tsm-rucklidge-static $dp _ $order $timestep $datalines  1 0 0  $p 2';;
    'rf')           cmd='./tsm-rf-static $dp _ $order $timestep $datalines  .05 -.05 .3  $p .1';;
    'bouali')       cmd='./tsm-bouali-static $dp _ $order $timestep $datalines  1 1 0  3 2.2 1 $p';;
    'gt')           cmd='./tsm-genesio-tesi-static $dp _ $order $timestep $datalines  .1 .1 .1  $p 1.1 1';;
    'wb')           cmd='./tsm-wimol-banlue-static $dp _ $order $timestep $datalines  1 0 0  $p';;
    'yw')           cmd='./tsm-yu-wang-static $dp _ $order $timestep $datalines  1 0 0  10 40 2 $p';;
    'minimal')      cmd='./tsm-sprott-minimal-static $dp _ $order $timestep $datalines  .02 0 0  $p';;
    *)              echo "chaos-scan-cns: Unknown ODE"; exit;;
esac

p=$start
while [ 1 -eq $(echo "$p < $end" | bc) ]
do
    echo -n "$p "
    eval ./cns both noplot "$cmd" >/dev/null 2>/dev/null
    ./chaos-distance-cns $((datalines + 1)) $lower $upper
    p=$(echo "$p + $step;" | bc)
done

