#!/bin/sh
#
#  (c) 2018-2021 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

for file in $(ls tsm-* h-* | grep -v '\.py$')
do
    [ -x $file ] && rm -f $file
done

rm -f divergence taylor-test dual-test

rm -f lib*.so *.o

echo OK
