#!/bin/sh
#
#  (c) 2018-2021 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

rm -rf coverage-out .coverage cov_html .pytest_cache __pycache__

for file in $(ls tsm-* h-* | grep -v '\.py$') divergence libad-test-dbg libdual-test-dbg
do
    [ -x $file ] && rm -f $file
done

rm -f lib*.so *.o
rm -f coverage.info *.gcov *.gcda *.gcno *.gch *_gprof gmon.out

echo OK
