#!/bin/sh

fileA='/tmp/dataA'
fileB='/tmp/dataB'

method=$1
shift
original=$*

halfstep () {
    start="$1 $2 $3"
    step=$(echo "scale=6; $4/2;" | bc)
    steps=$(echo "scale=0; $5*2;" | bc)
    shift 5
    end="$*"
    echo 'Better:' $start $step $steps $end
    $start $step $steps $end | sed -n '1~2p' >$fileA &
}

order1plus () {
    start="$1 $2"
    order=$(expr $3 + 1)
    shift 3
    end="$*"
    echo 'Better:' $start $order $end
    $start $order $end >$fileA &
}

orderstep () {
    start="$1 $2"
    order=$(expr $3 + 1)
    step=$(echo "scale=6; $4/2;" | bc)
    steps=$(echo "scale=0; $5*2;" | bc)
    shift 5
    end="$*"
    echo 'Better:' $start $order $step $steps $end
    $start $order $step $steps $end | sed -n '1~2p' >$fileA &
}

case $method in
    'step') halfstep $original;;
    'order') order1plus $original;;
    'both') orderstep $original;;
    'data') cp d-604-502-1400 $fileA;;
    *) echo "CNS: Bad Method"; exit 1;;
esac
$original >$fileB &
wait

./divergence.py $fileA $fileB 3 0.000000000000000001 >/dev/null
./divergence.py $fileA $fileB 3 0.000000000001 >/dev/null
./divergence.py $fileA $fileB 3 0.000000001 >/dev/null
./divergence.py $fileA $fileB 3 0.000001 >/dev/null
./divergence.py $fileA $fileB 3 0.001 >/dev/null
./divergence.py $fileA $fileB 3 1.0 >/dev/null

./compare.py $fileA $fileB 3 >/dev/null &

echo "splot '$fileA' with lines, '$fileB' with lines" | gnuplot -p

