#!/bin/sh
#
#  (c) 2018-2022 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#

echo "Clean Numerical Simulation: [$*]" >&2

method=$1
threshold=$2
shift 2

case $method in
    'step2') . ./cns-functions.sh
             processed="$(get_precision $*)"
             halfstep $processed
             $processed >$fileB &
             wait;;
    'nosim') ;;  # replot existing data
          *) echo "CNS: Bad Method, should be 'step2' or 'nosim'"; exit 1;;
esac

./divergence $fileA $fileB $threshold

./plotDiff.py $fileA $fileB $threshold 2>/dev/null &
