#!/bin/sh
#
#  (c) 2018-2022 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

echo "CNS duration vs Integrator Order: [$*]" >&2

min_order=$1
max_order=$2
threshold=$3
shift 3

case $4 in
    "_")  ;;
    *)    echo '"order" argument should be set to "_"'; exit 1;;
esac

. ./cns-functions.sh

processed="$(get_precision $*)"

n=$min_order
while [ $n -le $max_order ]
do
    set $processed
    begin="$1 $2 $3"
    shift 4
    current="$begin $n $*"
    halfstep $current
    $current >$fileB &
    wait
    temp=$(./divergence $fileA $fileB $threshold)
    case temp in
        '') echo $n "No more data - increase simulation time?"
            exit 1;;
         *) set $temp
            echo $n $4 $6;;
    esac
    n=$((n + 1))
done 2>/dev/null
exit 0
