#!/bin/sh

pytest --cov=ad --cov=plotters --cov-report html:cov_html ad_test.py solver_test.py -q
echo ""

c99 --coverage -O0 -o taylor-test taylor-test.c taylor-ode.c -lm
./taylor-test 6 4 4 -3

c99 --coverage -O0 -o dual-test dual-test.c dual.c -lm
./dual-test 6 _ 4 -3

lcov --capture --directory . --output-file coverage.info
genhtml coverage.info --output-directory coverage-out

echo "C:      file:///home/$USER/projects/ODE-Playground/coverage-out/index.html"
echo "Python: file:///home/$USER/projects/ODE-Playground/cov_html/index.html"

