#!/bin/sh

PYTHON_OUT='cov_html'
C_OUT_DIR='coverage-out'
C_OUT_FILE='coverage.info'

pytest --cov=ad --cov=plotters --cov-report html:$PYTHON_OUT ad_test.py solver_test.py -q
echo ""

c99 --coverage -O0 -o libad-test-dbg libad-test.c ad.c ode-common.c taylor-ode.c -lm
./libad-test-dbg 10 -.5 1e-12 >/dev/null
./libad-test-dbg 10 0 1e-12 >/dev/null
./libad-test-dbg 10 .5 1e-12 >/dev/null
./libad-test-dbg 10 1 1e-42 2 >/dev/null

c99 --coverage -O0 -o libdual-test-dbg libdual-test.c dual.c -lm
./libdual-test-dbg -.5 1e-12 >/dev/null
./libdual-test-dbg 0 1e-12 >/dev/null
./libdual-test-dbg .5 1e-12 >/dev/null
./libdual-test-dbg 1 1e-42 2 >/dev/null

lcov --capture --directory . --output-file $C_OUT_FILE
genhtml $C_OUT_FILE --output-directory $C_OUT_DIR

echo "C:      file://$(pwd)/$C_OUT_DIR/index.html"
echo "Python: file://$(pwd)/$PYTHON_OUT/index.html"
