#!/bin/sh

C_OUT_DIR='coverage-out'
C_OUT_FILE='coverage.info'

c99 --coverage -O0 -o libad-test-dbg libad-test.c ad.c taylor-ode.c -lmpfr
./libad-test-dbg 32 20 1 1e-18 0 >/dev/null

lcov --capture --directory . --output-file $C_OUT_FILE
genhtml $C_OUT_FILE --output-directory $C_OUT_DIR

echo "C:      file://$(pwd)/$C_OUT_DIR/index.html"
