#!/bin/sh
#set -x
ref=$1
shift
ode=$1
precision=$2
order=$3
step=$4
nsteps=$5
shift 5
parameters=$*

file='/tmp/data'

$ode $precision $order $step $nsteps $parameters >$file

./divergence.py $ref $file 3 0.000000000000000001 >/dev/null
./divergence.py $ref $file 3 0.000000000001 >/dev/null
./divergence.py $ref $file 3 0.000000001 >/dev/null
./divergence.py $ref $file 3 0.000001 >/dev/null
./divergence.py $ref $file 3 0.001 >/dev/null
./divergence.py $ref $file 3 1.0 >/dev/null

./compare.py $ref $file 3 >/dev/null &

exit

# Examples

./find_divergence data-ref ./tsm.py lorenz 9 10 .01 10001 -15.8 -17.48 35.64 10 28 8 3
