#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

user_dir="/tmp/$USER"
[ ! -d $user_dir ] && mkdir $user_dir
user_data="$user_dir/data"

choice=$(yad --columns=2 --title="ODE Playground (TSM)" --form --separator=" " --align=right \
    --field="Model:CB" \
    --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
    -- 'Newton!Spring!Analysis!^EightBody!FourBodyA!FourBodyB!ThreeBody!TwoBody' \
       '2000!1000..10000!1000' '8!2..10!2' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000')

case $? in
    1) exit;;
esac

set $choice
model=$1
shift
display_places=6
track_length=$1
shift
control=$*

plot_analysis () {
gnuplot -p << EOF
set key left
set terminal wxt size 600,450 background rgb "grey85"
set xrange [-0.1:1.1]
set yrange [-0.1:1.1]
set xlabel 'coordinate steps'
set ylabel 'momentum steps'
plot '$user_data' using 1:2 title 'time step sequence' with linespoints pt 7 ps 0
EOF
}

plot_hamiltonian_error () {
gnuplot -p << EOF
set key left
set terminal wxt size 600,450 background rgb "grey85"
set xlabel 'time'
set ylabel 'approximate places'
plot '$user_data' using $1:$2 with linespoints pt 7 ps 0
EOF
}

case $model in
    Newton)
        parameters=$(yad --title="Newtonian Orbit" --form --separator=" " --align=right \
        --field="mass" --field="r0" --field="L factor":NUM \
        -- "1" "12" '0.6!0.0..1.0!0.1!1')
        ./plot ./h-newton-std $display_places $1 $2 $3 $parameters; plot_hamiltonian_error 4 5 ;;
    Spring)
        parameters=$(yad --title="Mass-Spring System" --form --separator=" " --align=right \
        --field="mass" --field="spring constant" --field="length" \
        -- "1" "1" "1")
        ./plot ./h-spring-std $display_places $1 $2 $3 $parameters; plot_hamiltonian_error 4 5 ;;
    Analysis)
        ./h-analysis-std $display_places $1 1.0 1 >$user_data; plot_analysis ;;
    *Body*)
        case $model in
            EightBody) g=0.05
                bodies=$(yad --width=350 --height=280 --list --title="Eight Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=Mass --column=X --column=Y --column=Z --column=pX --column=pY --column=pZ \
                -- 100.0  0.0  0.0  0.0  0.0  0.0  0.0 \
                     2.0  0.0  4.5  0.4 -0.2  0.0  1.8 \
                     3.0 -6.0  0.0 -0.4  0.0 -2.0  1.0 \
                     5.0  3.0  0.0 -0.2  0.0  5.8 -0.2 \
                     4.0  0.0 -4.0  0.1 -3.6  0.0  0.2 \
                     3.0 -4.0  0.0 -0.1  0.0 -0.2 -2.6 \
                     3.0  8.0  0.0 -0.3  0.0  2.0 -0.2 \
                     4.0  0.0  4.0 -0.2 -4.8  0.0 -0.2) ;;
            FourBodyA) g=1
                bodies=$(yad --width=450 --height=180 --list --title="Four Body A" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0 0.0 -0.69548  0.69548  0.87546 -0.31950 -0.31950 \
                   1.0 0.0  0.69548 -0.69548  0.87546  0.31950  0.31950 \
                   1.0 0.0 -0.69548 -0.69548 -0.87546 -0.31950  0.31950 \
                   1.0 0.0  0.69548  0.69548 -0.87546  0.31950 -0.31950) ;;
            FourBodyB) g=3.5
                bodies=$(yad --width=350 --height=180 --list --title="Four Body B" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0  1.0  1.0  1.0 -1.0  1.0 -1.0 \
                   1.0 -1.0 -1.0  1.0  1.0 -1.0 -1.0 \
                   1.0  1.0 -1.0 -1.0  1.0  1.0  1.0 \
                   1.0 -1.0  1.0 -1.0 -1.0 -1.0  1.0) ;;
            ThreeBody) g=1
                bodies=$(yad --width=400 --height=150 --list --title="Three Body" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0 -1.6 0.0 0.0  0.08058  0.58884  0.2 \
                   1.0  1.6 0.0 0.0  0.08058  0.58884 -0.2 \
                   1.0  0.0 0.0 0.0 -0.16116 -1.17768  0.0) ;;
            TwoBody) g=4
                bodies=$(yad --width=350 --height=120 --list --title="Two Body" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0 0.0  1.0 0.0  1.0 0.0 0.0 \
                   1.0 0.0 -1.0 0.0 -1.0 0.0 0.0) ;;
        esac
        (./h-nbody-std $display_places $control $g $bodies >$user_data; plot_hamiltonian_error 1 2) &
        ./h-nbody-gl $track_length $control $g $bodies ;;
esac
