#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

choice=$(yad --columns=2 --title="Playground" --form --separator=" " --align=right \
    --field="Hamiltonian Model:CB" \
    -- 'Newton!Analysis!^EightBody!SixBody!FourBodyA!FourBodyB!ThreeBody!TwoBody')

case $? in
    1) exit;;
esac

set $choice
model=$1
shift
display_places=6

plot_analysis () {
/usr/bin/gnuplot << EOF
set key left
set terminal qt size 600,450
set xrange $3
set yrange $4
set xlabel '$5'
set ylabel '$6'
plot '$user_data' using $1:$2 with linespoints pt 7 ps 0
pause mouse close
EOF
}

plot_hamiltonian_error () {
/usr/bin/gnuplot << EOF
set key left
set terminal qt size 600,450
set yrange [37.0:0.0]
set xlabel 'time'
set ylabel 'approximate places'
plot '$user_data' using $1:$2 with linespoints pt 7 ps 0
pause mouse close
EOF
}

case $model in
    Newton)
        parameters=$(yad --columns=2 --title="Newtonian Orbit" --form --separator=" " --align=right \
        --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
        --field="GM" --field="m" --field="r0" --field="L factor":NUM \
        -- '8!2..16!2' '.1!0.001..1.0!0.001!3' '10000!1..1000000!1000' \
           '9.0' '5.0' '20.0' '0.6!0.0..1.0!0.1!1')
        time -p ./h-newton-std $display_places $parameters >$user_data
        plot_analysis 1 2 '[:]' '[:]' 'x' 'y' &
        plot_analysis 3 4 '[:]' '[:]' 'qr' 'pr' &
        plot_hamiltonian_error 5 6 & ;;
    Analysis)
        parameters=$(yad --title="Step Display" --form --separator=" " --align=right \
        --field="Order":NUM \
        -- '8!2..16!2')
        ./h-analysis-std $display_places $parameters 1.0 1 >$user_data;
        plot_analysis 1 2 '[-0.1:1.1]' '[-0.1:1.1]' 'coordinate steps' 'momentum steps' ;;
    *Body*)
        set $(yad --columns=2 --title="N-Body - Integrator Control" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
               '2000!1000..10000!1000' '8!2..16!2' '.01!0.001..1.0!0.001!3' '10000!1..1000000!1000')
        track_length=$1
        shift
        control=$*
        case $model in
            EightBody) g=$(yad --title="Eight Body - G" --form --separator=" " --align=right \
                --field="Gravitational Constant" -- '0.050')
                bodies=$(yad --width=350 --height=280 --list --title="Eight Body - Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=Mass --column=X --column=Y --column=Z --column=pX --column=pY --column=pZ \
                -- 100.0  0.0  0.0  0.0  0.0  0.0  0.0 \
                     2.0  0.0  4.5  0.4 -0.2  0.0  1.8 \
                     3.0 -6.0  0.0 -0.4  0.0 -2.0  1.0 \
                     5.0  3.0  0.0 -0.2  0.0  5.8 -0.2 \
                     4.0  0.0 -4.0  0.1 -3.6  0.0  0.2 \
                     3.0 -4.0  0.0 -0.1  0.0 -0.2 -2.6 \
                     3.0  8.0  0.0 -0.3  0.0  2.0 -0.2 \
                     4.0  0.0  4.0 -0.2 -4.8  0.0 -0.2) ;;
            SixBody) g=$(yad --title="Six Body - G" --form --separator=" " --align=right \
                --field="Gravitational Constant" -- '10.00')
                bodies=$(yad --width=350 --height=280 --list --title="Six Body - Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=Mass --column=X --column=Y --column=Z --column=pX --column=pY --column=pZ \
                -- 1.0  10.0   0.0   0.0  0.0  1.0  0.0 \
                   1.0 -10.0   0.0   0.0  0.0 -1.0  0.0 \
                   1.0   0.0  10.0   0.0  0.0  0.0  1.0 \
                   1.0   0.0 -10.0   0.0  0.0  0.0 -1.0 \
                   1.0   0.0   0.0  10.0  1.0  0.0  0.0 \
                   1.0   0.0   0.0 -10.0 -1.0  0.0  0.0) ;;
            FourBodyA) g=$(yad --title="Four Body A - G" --form --separator=" " --align=right \
                --field="Gravitational Constant" -- '1.000')
                bodies=$(yad --width=450 --height=180 --list --title="Four Body A - Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0 0.0 -0.69548  0.69548  0.87546 -0.31950 -0.31950 \
                   1.0 0.0  0.69548 -0.69548  0.87546  0.31950  0.31950 \
                   1.0 0.0 -0.69548 -0.69548 -0.87546 -0.31950  0.31950 \
                   1.0 0.0  0.69548  0.69548 -0.87546  0.31950 -0.31950) ;;
            FourBodyB) g=$(yad --title="Four Body B - G" --form --separator=" " --align=right \
                --field="Gravitational Constant" -- '4.000')
                bodies=$(yad --width=350 --height=180 --list --title="Four Body B - Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0  1.0  1.0  1.0 -1.0  1.0 -1.0 \
                   1.0 -1.0 -1.0  1.0  1.0 -1.0 -1.0 \
                   1.0  1.0 -1.0 -1.0  1.0  1.0  1.0 \
                   1.0 -1.0  1.0 -1.0 -1.0 -1.0  1.0) ;;
            ThreeBody) g=$(yad --title="Three Body - G" --form --separator=" " --align=right \
                --field="Gravitational Constant" -- '1.000')
                bodies=$(yad --width=400 --height=150 --list --title="Three Body - Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0 -1.6 0.0 0.0  0.08058  0.58884  0.2 \
                   1.0  1.6 0.0 0.0  0.08058  0.58884 -0.2 \
                   1.0  0.0 0.0 0.0 -0.16116 -1.17768  0.0) ;;
            TwoBody) g=$(yad --title="Two Body - G" --form --separator=" " --align=right \
                --field="Gravitational Constant" -- '10.00')
                bodies=$(yad --width=350 --height=120 --list --title="Two Body - Bodies" --separator=" " \
                --print-all --grid-lines=BOTH --no-click --editable \
                --column=mass --column=x --column=y --column=z --column=px --column=py --column=pz \
                -- 1.0  1.0  0.0  0.0  0.0  1.0  0.0 \
                   1.0 -1.0  0.0  0.0  0.0 -1.0  0.0) ;;
        esac
        (time -p ./h-nbody-std $display_places $control $g $bodies >$user_data; plot_hamiltonian_error 1 2) &
        ./h-nbody-gl $track_length $control $g $bodies ;;
esac
