#!/bin/sh
#
#  (c) 2018-2020 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#
#  Example: ./ic .001 noplot ./tsm-thomas-static 15 _ 10 0.1 30000 1 0 0 .185
#

fileA='/tmp/dataA'
fileB='/tmp/dataB'
fileC='/tmp/dataC'
fileD='/tmp/dataD'
fileE='/tmp/dataE'
fileF='/tmp/dataF'
fileG='/tmp/dataG'

delta=$1
plot=$2
shift 2

perturb () {
    start="$1 $2 $3 $4 $5 $6"
    x0=$7
    y0=$8
    z0=$9
    shift 9
    end="$*"
    echo 'oo' $start $x0 $y0 $z0 $end
    $start $x0 $y0 $z0 $end >$fileG 2>/dev/null &
    y=$y0
    z=$z0
    x=$(echo "scale=32; $x0 + $delta;" | bc)
    echo 'x+' $start $x $y $z $end
    $start $x $y $z $end >$fileA 2>/dev/null &
    x=$(echo "scale=32; $x0 - $delta;" | bc)
    echo 'x-' $start $x $y $z $end
    $start $x $y $z $end >$fileB 2>/dev/null &
    x=$x0
    z=$z0
    y=$(echo "scale=32; $y0 + $delta;" | bc)
    echo 'y+' $start $x $y $z $end
    $start $x $y $z $end >$fileC 2>/dev/null &
    y=$(echo "scale=32; $y0 - $delta;" | bc)
    echo 'y-' $start $x $y $z $end
    $start $x $y $z $end >$fileD 2>/dev/null &
    x=$x0
    y=$y0
    z=$(echo "scale=32; $z0 + $delta;" | bc)
    echo 'z+' $start $x $y $z $end
    $start $x $y $z $end >$fileE 2>/dev/null &
    z=$(echo "scale=32; $z0 - $delta;" | bc)
    echo 'z-' $start $x $y $z $end
    $start $x $y $z $end >$fileF 2>/dev/null &
}

perturb $*
wait

if [ "x$plot" = "xplot" ]
then
    ./plot3d.py $fileA $fileB $fileC $fileD $fileE $fileF $fileG >/dev/null 2>&1 &
fi

