#!/bin/sh

# Copyright (c) 2018-2020, Ian Smith (m4r35n357)
# All rights reserved.
# For licencing see LICENCE file
#

fileA='/tmp/dataA'
fileB='/tmp/dataB'
fileC='/tmp/dataC'
fileD='/tmp/dataD'
fileE='/tmp/dataE'
fileF='/tmp/dataF'

delta=$1
shift

perturb () {
    start="$1 $2 $3 $4 $5 $6"
    x0=$7
    y0=$8
    z0=$9
    shift 9
    end="$*"
    y=$y0
    z=$z0
    x=$(echo "scale=32; $x0 + $delta;" | bc)
    echo 'x+' $start $x $y $z $end
    $start $x $y $z $end >$fileA 2>/dev/null &
    x=$(echo "scale=32; $x0 - $delta;" | bc)
    echo 'x-' $start $x $y $z $end
    $start $x $y $z $end >$fileB 2>/dev/null &
    x=$x0
    z=$z0
    y=$(echo "scale=32; $y0 + $delta;" | bc)
    echo 'y+' $start $x $y $z $end
    $start $x $y $z $end >$fileC 2>/dev/null &
    y=$(echo "scale=32; $y0 - $delta;" | bc)
    echo 'y-' $start $x $y $z $end
    $start $x $y $z $end >$fileD 2>/dev/null &
    x=$x0
    y=$y0
    z=$(echo "scale=32; $z0 + $delta;" | bc)
    echo 'z+' $start $x $y $z $end
    $start $x $y $z $end >$fileE 2>/dev/null &
    z=$(echo "scale=32; $z0 - $delta;" | bc)
    echo 'z-' $start $x $y $z $end
    $start $x $y $z $end >$fileF 2>/dev/null &
}

perturb $*
wait

./plot3d.py $fileA $fileB $fileC $fileD $fileE $fileF >/dev/null 2>&1 &

