#!/bin/sh

choice=$(yad --columns=2 --title="ODE Playground (TSM)" --form --separator=" " --align=right \
    --field="Model:CB" \
    --field="Display Mode":CB --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
    -- '^EightBody!ThreeBody' \
       '0!1!2' '8!2..10!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000')

set $choice
model=$1
shift

case $model in
    EightBody)
        ./h-nbody-gl $* .05 $(yad --list --separator=" " --print-all --grid-lines=BOTH --no-click --editable --column=mass --column=qx --column=qy --column=qz --column=px --column=py --column=pz -- 100.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 0.0 4.5 0.4 -0.2 0.0 1.8 3.0 -6.0 0.0 -0.4 0.0 -2.0 1.0 5.0 3.0 0.0 -0.2 0.0 5.8 -0.2 4.0 0.0 -4.0 0.1 -3.6 0.0 0.2 3.0 -4.0 0.0 -0.1 0.0 -0.2 -2.6 3.0 8.0 0.0 -0.3 0.0 2.0 -0.2 4.0 0.0 4.0 -0.2 -4.8 0.0 -0.2)
    ;;
    ThreeBody)
        ./h-nbody-gl $* 1 $(yad --list --separator=" " --print-all --grid-lines=BOTH --no-click --editable --column=mass --column=qx --column=qy --column=qz --column=px --column=py --column=pz -- 1.0 -1.0 0.0 0.0 0.08058 0.58884 0.2 1.0 1.0 0.0 0.0 0.08058 0.58884 -0.2 1.0 0.0 0.0 0.0 -0.16116 -1.17768 0.0)
    ;;
esac
