#!/bin/sh

user_dir="/tmp/$USER"
[ ! -d $user_dir ] && mkdir $user_dir
user_data="$user_dir/data"

choice=$(yad --columns=2 --title="ODE Playground (TSM)" --form --separator=" " --align=right \
    --field="Model:CB" --field="Analysis type:CB" \
    -- 'Lorenz!Rossler!^Thomas!RF!Halvorsen' \
       '^GLplot!Gnuplot3D!Gnuplot2D!CNS!CNSscan!Bifurcation')

case $? in
    1) exit;;
esac

set $choice
model=$1
analysis=$2

gnuplot3d () {
gnuplot -p << EOF
set xyplane 0
set view 54.73561,135
set xlabel 'X'
set ylabel 'Y'
set zlabel 'Z'
splot '$user_data' with lines
EOF
}

gnuplot2d () {
gnuplot -p << EOF
set terminal wxt size 1200,900
plot '$user_data' using 4:1 with lines, '' u 4:2 w l, '' u 4:3 w l
EOF
}

missing () {
    yad --image "dialog-warning" --title "Alert" --button=gtk-ok:0 --text "Not implemented yet"
}

case $model in
    Lorenz)
        case $analysis in
            GLplot) ./tsm-lorenz-gl _ \
                $(yad --columns=2 --title="Lorenz Attractor OpenGL (TSM)" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="sigma" --field="rho" --field="beta (numerator)" --field="beta (denominator)" \
                --  '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '-15.8' '-18.48' '35.64' \
                    '10' '28' '8' '3')
            ;;
            Gnuplot3D|Gnuplot2D)
                missing
            ;;
            CNS) ./cns \
                $(yad --columns=2 --title="Lorenz CNS (TSM)" --form --separator=" " --align=right \
                --field="Mode":CB --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="sigma" --field="rho" --field="beta (numerator)" --field="beta (denominator)" \
                --  'step2!nosim' '1.0' './tsm-lorenz-static!./tsm-lorenz-dbg!./tsm-lorenz' \
                    '6!0..36!3' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '-15.8' '-18.48' '35.64' \
                    '10' '28' '8' '3')
            ;;
            CNSscan) ./cns-scan \
                $(yad --columns=2 --title="Lorenz CNS Scan (TSM)" --form --separator=" " --align=right \
                --field="Maxium Order":NUM --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="sigma" --field="rho" --field="beta (numerator)" --field="beta (denominator)" \
                --  '32!2..32!1' '1.0' './tsm-lorenz-static!./tsm-lorenz-dbg!./tsm-lorenz' \
                    '6!0..36!3' '_' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '-15.8' '-18.48' '35.64' \
                    '10' '28' '8' '3') | tee $user_data
            ;;
            Bifurcation) ./bifurcation-scan \
                $(yad --columns=2 --title="Lorenz Bifurcation (TSM)" --form --separator=" " --align=right \
                --field="Lower Value" --field="Upper Value" --field="Skip Transient" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="sigma" --field="rho:RO" --field="beta (numerator)" --field="beta (denominator)" \
                --  '0.0' '50.0' '10' './tsm-lorenz-static!./tsm-lorenz-dbg!./tsm-lorenz' \
                    '6!0..36!3' '4!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '-15.8' '-18.48' '35.64' \
                    '10' '$p' '8' '3')
            ;;
        esac
    ;;
    Rossler)
        case $analysis in
            GLplot) ./tsm-rossler-gl _ \
                $(yad --columns=2 --title="Rossler Attractor OpenGL (TSM)" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" --field="c" \
                --  '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '0.0' '-6.78' '0.02' \
                    '.2' '.2' '5.7')
            ;;
            Gnuplot3D|Gnuplot2D)
                missing
            ;;
            CNS) ./cns \
                $(yad --columns=2 --title="Rossler CNS (TSM)" --form --separator=" " --align=right \
                --field="Mode":CB --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" --field="c" \
                --  'step2!nosim' '1.0' './tsm-rossler-static!./tsm-rossler-dbg!./tsm-rossler' \
                    '6!0..36!3' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '0.0' '-6.78' '0.02' \
                    '.2' '.2' '5.7')
            ;;
            CNSscan) ./cns-scan \
                $(yad --columns=2 --title="Rossler CNS Scan (TSM)" --form --separator=" " --align=right \
                --field="Maxium Order":NUM --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" --field="c" \
                --  '32!2..32!1' '1.0' './tsm-rossler-static!./tsm-rossler-dbg!./tsm-rossler' \
                    '6!0..36!3' '_' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '0.0' '-6.78' '0.02' \
                    '.2' '.2' '5.7') | tee $user_data
            ;;
            Bifurcation) ./bifurcation-scan \
                $(yad --columns=2 --title="Rossler Bifurcation (TSM)" --form --separator=" " --align=right \
                --field="Lower Value" --field="Upper Value" --field="Skip Transient" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" --field="c":RO \
                --  '0.0' '50.0' '10' './tsm-rossler-static!./tsm-rossler-dbg!./tsm-rossler' \
                    '6!0..36!3' '4!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '0.0' '-6.78' '0.02' \
                    '.2' '.2' '$p')
            ;;
        esac
    ;;
    Thomas)
        case $analysis in
            GLplot) ./tsm-thomas-gl _ \
                $(yad --columns=2 --title="Thomas Attractor OpenGL (TSM)" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="b" \
                --  '8!4..32!1' '.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '0.185')
            ;;
            Gnuplot3D|Gnuplot2D)
                $(yad --columns=2 --title="Thomas Attractor Gnuplot (TSM)" --form --separator=" " --align=right \
                --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="b" \
                --  './tsm-thomas-static!./tsm-thomas-dbg!./tsm-thomas' \
                    '6!0..36!3' '8!4..32!1' '.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '0.185') >$user_data
                case $analysis in
                    Gnuplot3D) gnuplot3d;;
                    Gnuplot2D) gnuplot2d;;
                esac
            ;;
            CNS) ./cns \
                $(yad --columns=2 --title="Thomas CNS (TSM)" --form --separator=" " --align=right \
                --field="Mode":CB --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="b" \
                --  'step2!nosim' '1.0' './tsm-thomas-static!./tsm-thomas-dbg!./tsm-thomas' \
                    '6!0..36!3' '8!4..32!1' '.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '0.185')
            ;;
            CNSscan) ./cns-scan \
                $(yad --columns=2 --title="Thomas CNS Scan (TSM)" --form --separator=" " --align=right \
                --field="Maxium Order":NUM --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="b" \
                --  '32!2..64!1' '1.0' './tsm-thomas-static!./tsm-thomas-dbg!./tsm-thomas' \
                    '6!0..36!3' '_' '.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '0.185') | tee $user_data
            ;;
            Bifurcation) ./bifurcation-scan 
                $(yad --columns=2 --title="Thomas Bifurcation (TSM)" --form --separator=" " --align=right \
                --field="Lower Value" --field="Upper Value" --field="Skip Transient" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="b:RO" \
                --  '0.1' '0.23' '10' './tsm-thomas-static!./tsm-thomas-dbg!./tsm-thomas' \
                    '6!0..36!3' '4!4..32!1' '.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '$p')
            ;;
        esac
    ;;
    RF)
        case $analysis in
            GLplot) ./tsm-rf-gl _ \
                $(yad --columns=2 --title="Rabinovich–Fabrikant Attractor OpenGL (TSM)" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="alpha" --field="gamma" \
                --  '8!4..32!1' '.01!0.001..0.1!0.001!3' '50000!1..1000000!1000' \
                    '0.05' '-0.05' '0.3' \
                    '.2873' '.1')
            ;;
            Gnuplot3D|Gnuplot2D)
                $(yad --columns=2 --title="Rabinovich–Fabrikant Gnuplot (TSM)" --form --separator=" " --align=right \
                --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="alpha" --field="gamma" \
                --  './tsm-rf-static!./tsm-rf-dbg!./tsm-rf!./tsm-rf-gl' \
                    '6!0..36!3' '8!4..32!1' '0.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '0.05' '-0.05' '0.3' \
                    '.2873' '.1') >$user_data
                case $analysis in
                    Gnuplot3D) gnuplot3d;;
                    Gnuplot2D) gnuplot2d;;
                esac
            ;;
            CNS) ./cns \
                $(yad --columns=2 --title="Rabinovich–Fabrikant CNS (TSM)" --form --separator=" " --align=right \
                --field="Mode":CB --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="alpha" --field="gamma" \
                --  'step2!nosim' '1.0' './tsm-rf-static!./tsm-rf-dbg!./tsm-rf!./tsm-rf-gl' \
                    '6!0..36!3' '8!4..32!1' '0.1!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '0.05' '-0.05' '0.3' \
                    '.2873' '.1')
            ;;
            CNSscan) ./cns-scan \
                $(yad --columns=2 --title="Rabinovich–Fabrikant CNS Scan (TSM)" --form --separator=" " --align=right \
                --field="Maxium Order":NUM --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="alpha" --field="gamma" \
                --  '32!2..64!1' '1.0' './tsm-rf-static!./tsm-rf-dbg!./tsm-rf' \
                    '6!0..36!3' '_' '.01!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '0.05' '-0.05' '0.3' \
                    '.2873' '.1') | tee $user_data
            ;;
            Bifurcation) ./bifurcation-scan \
                $(yad --columns=2 --title="Rabinovich–Fabrikant Bifurcation (TSM)" --form --separator=" " --align=right \
                --field="Lower Value" --field="Upper Value" --field="Skip Transient" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="alpha":RO --field="gamma" \
                --  '0.1' '0.23' '10' './tsm-rf-static!./tsm-rf-dbg!./tsm-rf' \
                    '6!0..36!3' '4!4..32!1' '.01!0.001..0.1!0.001!3' '30000!1..1000000!1000' \
                    '0.05' '-0.05' '0.3' \
                    '$p' '.1')
            ;;
        esac
    ;;
    Halvorsen)
        case $analysis in
            GLplot) ./tsm-halvorsen-gl _ \
                $(yad --columns=2 --title="Halvorsen Attractor OpenGL (TSM)" --form --separator=" " --align=right \
                --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" \
                --  '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '1.4' '4')
            ;;
            Gnuplot3D|Gnuplot2D)
                $(yad --columns=2 --title="Halvorsen Gnuplot (TSM)" --form --separator=" " --align=right \
                --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" \
                --  './tsm-halvorsen-static!./tsm-halvorsen-dbg!./tsm-halvorsen' \
                    '6!0..36!3' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '1.4' '4') >$user_data
                case $analysis in
                    Gnuplot3D) gnuplot3d;;
                    Gnuplot2D) gnuplot2d;;
                esac
            ;;
            CNS) ./cns \
                $(yad --columns=2 --title="Halvorsen CNS (TSM)" --form --separator=" " --align=right \
                --field="Mode":CB --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" \
                --  'step2!nosim' '1.0' './tsm-halvorsen-static!./tsm-halvorsen-dbg!./tsm-halvorsen' \
                    '6!0..36!3' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '1.4' '4')
            ;;
            CNSscan) ./cns-scan \
                $(yad --columns=2 --title="Halvorsen CNS Scan (TSM)" --form --separator=" " --align=right \
                --field="Maxium Order":NUM --field="Separation" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a" --field="b" \
                --  '32!2..64!1' '1.0' './tsm-halvorsen-static!./tsm-halvorsen-dbg!./tsm-halvorsen' \
                    '6!0..36!3' '_' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '1.4' '4') | tee $user_data
            ;;
            Bifurcation) ./bifurcation-scan \
                $(yad --columns=2 --title="Halvorsen Bifurcation (TSM)" --form --separator=" " --align=right \
                --field="Lower Value" --field="Upper Value" --field="Skip Transient" --field="Model:CB" \
                --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
                --field="x0" --field="y0" --field="z0" \
                --field="a:RO" --field="b" \
                --  '1' '4' '10' './tsm-halvorsen-static!./tsm-halvorsen-dbg!./tsm-halvorsen' \
                    '6!0..36!3' '4!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                    '1.0' '0.0' '0.0' \
                    '$p' '4')
            ;;
        esac
    ;;
esac
