#!/bin/sh
#
#  (c) 2018-2023 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

user_dir="/tmp/$USER"
[ ! -d $user_dir ] && mkdir $user_dir
user_data="$user_dir/data"

choice=$(yad --columns=2 --title="ODE Playground" --form --separator=" " --align=right \
    --field="Model:CB" --field="Analysis type:CB" \
    -- 'Halvorsen!Lorenz!RF!^Thomas' '^GLplot!IC!Animated!Gnuplot!CNS!CNSScan')

case $? in
    1) exit;;
esac

set $choice
model=$1
analysis=$2

case $model in
    Lorenz) case $analysis in
        GLplot) ./tsm-lorenz.py $(yad --columns=2 --title="Lorenz" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="sigma" --field="rho" --field="beta(n)" --field="beta(d)" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '-15.8' '-18.48' '35.64' '10' '28' '8' '3') | ./plot3d.py ;;
        IC) ./ic .001 32 ./tsm-lorenz.py $(yad --columns=2 --title="Lorenz" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="sigma" --field="rho" --field="beta(n)" --field="beta(d)" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '-15.8' '-18.48' '35.64' '10' '28' '8' '3') | ./plot3d.py ;;
        Animated) ./tsm-lorenz.py $(yad --columns=2 --title="Lorenz" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="sigma" --field="rho" --field="beta(n)" --field="beta(d)" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '-15.8' '-18.48' '35.64' '10' '28' '8' '3') | ./plotAnimated.py -30 50 ;;
        Gnuplot) ./plot ./tsm-lorenz.py $(yad --columns=2 --title="Lorenz" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="sigma" --field="rho" --field="beta(n)" --field="beta(d)" \
            --  '6!0..36!3' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '-15.8' '-18.48' '35.64' '10' '28' '8' '3') ;;
        CNS) ./cns $(yad --columns=2 --title="Lorenz" --form --separator=" " --align=right \
            --field="Mode":CB --field="Separation" --field="Model":CB \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="sigma" --field="rho" --field="beta(n)" --field="beta(d)" \
            --  'step2!nosim' '1.0' './tsm-lorenz.py!./rk4-lorenz.py' \
                '6!0..36!3' '8!1..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '-15.8' '-18.48' '35.64' '10' '28' '8' '3') ;;
        CNSScan) ./cns-scan $(yad --columns=2 --title="Lorenz" --form --separator=" " --align=right \
            --field="Maximum Order":NUM --field="Separation" --field="Model":RO \
            --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="sigma" --field="rho" --field="beta(n)" --field="beta(d)" \
            --  '16!2..32!1' '1.0' './tsm-lorenz.py' \
                '6!0..36!3' '_' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '-15.8' '-18.48' '35.64' '10' '28' '8' '3') ;;
    esac ;;
    Thomas) case $analysis in
        GLplot) ./tsm-thomas.py $(yad --columns=2 --title="Thomas" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="b" \
            --  '6!0..36!3' '8!4..32!1' '.1!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '0.185') | ./plot3d.py ;;
        IC) ./ic .001 32 ./tsm-thomas.py $(yad --columns=2 --title="Thomas" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="b" \
            --  '6!0..36!3' '8!4..32!1' '.1!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '0.185') | ./plot3d.py ;;
        Animated) ./tsm-thomas.py $(yad --columns=2 --title="Thomas" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="b" \
            --  '6!0..36!3' '8!4..32!1' '.1!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '0.185') | ./plotAnimated.py -5 5 ;;
        Gnuplot) ./plot ./tsm-thomas.py $(yad --columns=2 --title="Thomas" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="b" \
            --  '6!0..36!3' '8!4..32!1' '.1!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '0.185') ;;
        CNS) ./cns $(yad --columns=2 --title="Thomas" --form --separator=" " --align=right \
            --field="Mode":CB --field="Separation" --field="Model":CB \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="b" \
            --  'step2!nosim' '1.0' './tsm-thomas.py!./rk4-thomas.py' \
                '6!0..36!3' '8!1..32!1' '.1!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '0.185') ;;
        CNSScan) ./cns-scan $(yad --columns=2 --title="Thomas" --form --separator=" " --align=right \
            --field="Maximum Order":NUM --field="Separation" --field="Model":RO \
            --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="b" \
            --  '16!2..64!1' '1.0' './tsm-thomas.py' \
                '6!0..36!3' '_' '.1!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '0.185') ;;
    esac ;;
    RF) case $analysis in
        GLplot) ./tsm-rf.py $(yad --columns=2 --title="Rabinovich–Fabrikant" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="alpha" --field="gamma" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '100000!1..1000000!1000' \
                '0.05' '-0.05' '0.3' '.2875' '.1') | ./plot3d.py ;;
        IC) ./ic .001 32  ./tsm-rf.py $(yad --columns=2 --title="Rabinovich–Fabrikant" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="alpha" --field="gamma" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '100000!1..1000000!1000' \
                '0.05' '-0.05' '0.3' '.2875' '.1') | ./plot3d.py ;;
        Animated) ./tsm-rf.py $(yad --columns=2 --title="Rabinovich–Fabrikant" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="alpha" --field="gamma" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '100000!1..1000000!1000' \
                '0.05' '-0.05' '0.3' '.2875' '.1') | ./plotAnimated.py -3 3 ;;
        Gnuplot) ./plot ./tsm-rf.py $(yad --columns=2 --title="Rabinovich–Fabrikant" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="alpha" --field="gamma" \
            --  '6!0..36!3' '8!4..32!1' '0.01!0.001..0.1!0.001!3' '100000!1..1000000!1000' \
                '0.05' '-0.05' '0.3' '.2875' '.1') ;;
        CNS) ./cns $(yad --columns=2 --title="Rabinovich–Fabrikant" --form --separator=" " --align=right \
            --field="Mode":CB --field="Separation" --field="Model":CB \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="alpha" --field="gamma" \
            --  'step2!nosim' '1.0' './tsm-rf.py!./rk4-rf.py' \
                '6!0..36!3' '8!1..32!1' '0.01!0.001..0.1!0.001!3' '100000!1..1000000!1000' \
                '0.05' '-0.05' '0.3' '.2875' '.1') ;;
        CNSScan) ./cns-scan $(yad --columns=2 --title="Rabinovich–Fabrikant" --form --separator=" " --align=right \
            --field="Maximum Order":NUM --field="Separation" --field="Model":RO \
            --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="alpha" --field="gamma" \
            --  '16!2..64!1' '1.0' './tsm-rf.py' \
                '6!0..36!3' '_' '0.01!0.001..0.1!0.001!3' '100000!1..1000000!1000' \
                '0.05' '-0.05' '0.3' '.2875' '.1') ;;
    esac ;;
    Halvorsen) case $analysis in
        GLplot) ./tsm-halvorsen.py $(yad --columns=2 --title="Halvorsen" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="a" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '1.4') | ./plot3d.py ;;
        IC) ./ic .001 32  ./tsm-halvorsen.py $(yad --columns=2 --title="Halvorsen" --form --separator=" " --align=right \
            --field="Trail Length":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="a" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '1.4') | ./plot3d.py ;;
        Animated) ./tsm-halvorsen.py $(yad --columns=2 --title="Halvorsen" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="a" \
            --  '5000!1000..10000!1000' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '1.4') | ./plotAnimated.py -15 10 ;;
        Gnuplot) ./plot ./tsm-halvorsen.py $(yad --columns=2 --title="Halvorsen" --form --separator=" " --align=right \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="a" \
            --  '6!0..36!3' '8!4..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '1.4') ;;
        CNS) ./cns $(yad --columns=2 --title="Halvorsen" --form --separator=" " --align=right \
            --field="Mode":CB --field="Separation" --field="Model":CB \
            --field="Display Places":NUM --field="Order":NUM --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="a" \
            --  'step2!nosim' '1.0' './tsm-halvorsen.py!./rk4-halvorsen.py' \
                '6!0..36!3' '8!1..32!1' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '1.4') ;;
        CNSScan) ./cns-scan $(yad --columns=2 --title="Halvorsen" --form --separator=" " --align=right \
            --field="Maximum Order":NUM --field="Separation" --field="Model":RO \
            --field="Display Places":NUM --field="Order":RO --field="Step Size":NUM --field="Steps":NUM \
            --field="x0" --field="y0" --field="z0" --field="a" \
            --  '16!2..64!1' '1.0' './tsm-halvorsen.py' \
                '6!0..36!3' '_' '.01!0.001..0.1!0.001!3' '10000!1..1000000!1000' \
                '1.0' '0.0' '0.0' '1.4') ;;
    esac ;;
esac
