#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if pytest ad_test.py solver_test.py -q
then
	exit 0
else
	echo "Commit failed!"
	exit 1
fi

