#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Running Python tests . . ."
if ! pytest ad_test.py solver_test.py -q
then
	echo "Python tests failed!"
	exit 1
fi

echo "Running Clang build . . ."
if ! ./build clang >/dev/null
then
	echo "c build failed!"
	exit 1
fi

echo "Running Lorenz executables . . ."
if ! ./tsm-lorenz-dbg 16 16 .01 10000 -15.8 -17.48 35.64 10 28 8 3 >/dev/null
then
	echo "Lorenz(DBG) failed!"
	exit 1
fi

if ! ./tsm-lorenz-static 16 16 .01 10000 -15.8 -17.48 35.64 10 28 8 3 >/dev/null
then
	echo "Lorenz(STATIC) failed!"
	exit 1
fi

if ! ./tsm-lorenz-dynamic 16 16 .01 10000 -15.8 -17.48 35.64 10 28 8 3 >/dev/null
then
	echo "Lorenz failed!"
	exit 1
fi

echo "OK to commit"
exit 0

