#!/bin/sh
#
#  Example: ./profile-kerr ./h-kerr-gl 0 8 0.010 10000 1000 0.8 1.0 0.9455050956749083 1.434374509531738 1.0 7.978759958927879 12.0 63.0
#
#  (c) 2018-2022 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

shift
progname="h_kerr_gl_gprof"

uname -a
/usr/bin/gcc --version

/usr/bin/gcc -std=c99 -Wall -pg -g -o $progname dual.c symplectic.c opengl.c h-kerr.c h-kerr-gl.c -lm -lGLEW -lglut -lGLU -lGL

time -p ./$progname $* >/dev/null

/usr/bin/gprof -p -b ./$progname gmon.out
