#!/bin/sh
#
#  Example: ./profile-tsm thomas 0 10 0.1 300000 1 0 0 .19
#
#  (c) 2018-2022 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

model=$1
shift
args=$*

progname="tsm_${model}_gl_gprof"

uname -a
/usr/bin/gcc --version

/usr/bin/gcc -Wall -pg -g -o $progname tsm-${model}.c taylor-ode.c opengl.c ode-gl.c -lm -lGLEW -lglut -lGLU -lGL

time -p ./$progname $args >/dev/null

/usr/bin/gprof -p -b ./$progname gmon.out
