#!/bin/sh
#
#  Example: ./return-map X  # data taken from /tmp/$USER/data
#
#  (c) 2018-2021 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

data="/tmp/$USER/data"
map="/tmp/$USER/map"

coordinate=$1

previous=0
grep $coordinate $data | while read x y z remainder
do
    case $coordinate in
        X|x) echo $previous $x; previous=$x;;
        Y|y) echo $previous $y; previous=$y;;
        Z|z) echo $previous $z; previous=$z;;
        *) exit;;
    esac
done >$map

gnuplot -p -e "set terminal wxt size 800,600; plot '$map' using 1:2 with points pt 0"
