#!/bin/sh
# Lorenz system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    return sigma * (y[k] - x[k])
}

define ode_y () {
    return rho * x[k] - mul(x[], z[]) - y[k]
}

define ode_z () {
    return mul(x[], y[]) - beta * z[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; sigma = $8; rho = $9; beta = ${10}/${11}
tsm($2, $3, $4)
EOF
