#!/bin/sh
# Rossler system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
scale=$1; n=$2; h=$3; steps=$4; x=$5; y=$6; z=$7; a=$8; b=$9; c=${10}
output(x, y, z, 0.0)
for (step = 1; step <= steps; step++) {
    x[0] = x; y[0] = y; z[0] = z
    for (k = 0; k < n; k++) {
        x[k + 1] = - (y[k] + z[k]) / (k + 1)
        y[k + 1] = (x[k] + a * y[k]) / (k + 1)
        z[k + 1] = (const(b, k) + mul(x[], z[], k) - c * z[k]) / (k + 1)
    }
    x = horner(n, x[], h); y = horner(n, y[], h); z = horner(n, z[], h)
    output(x, y, z, h * step)
}
EOF
