#!/bin/sh
# Bouali system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    sa[k] = const(1) - y[k]
    return a * mul(x[], sa[]) - b * z[k]
}

define ode_y () {
    sb[k] = const(1) - mul(x[], x[])
    return - c * mul(y[], sb[])
}

define ode_z () {
    return d * x[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; a = $8; b = $9; c = ${10}; d = ${11}
tsm($2, $3, $4)
EOF
