#!/bin/sh
# Burke-Shaw system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    return - s * (x[k] + y[k])
}

define ode_y () {
    return - s * mul(x[], z[]) - y[k]
}

define ode_z () {
    return s * mul(x[], y[]) + const(v)
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; s = $8; v = $9
tsm($2, $3, $4)
EOF
