#!/bin/sh
# Yu-Wang System
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc -l taylor.bc << EOF
define ode_x () {
    return a * (y[k] - x[k])
}

define ode_y () {
    return b * x[k] - c * mul(x[], z[])
}

define ode_z () {
    xy[k] = mul(x[], y[])
    exp(e_xy[], xy[])
    return e_xy[k] - d * z[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; a = $8; b = $9; c = ${10}; d = ${11}
tsm($2, $3, $4)
EOF
