#!/bin/sh
# Rossler system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    return - y[k] - z[k]
}

define ode_y () {
    return x[k] + a * y[k]
}

define ode_z () {
    return const(b) + mul(x[], z[]) - c * z[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; a = $8; b = $9; c = ${10}
tsm($2, $3, $4)
EOF
