#!/bin/sh
# Thomas system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc -l taylor.bc << EOF
define ode_x () {
    sy[k] = sin(cy[], y[])
    cy[k] = cos(sy[], y[])
    return sy[k] - b * x[k]
}

define ode_y () {
    sz[k] = sin(cz[], z[])
    cz[k] = cos(sz[], z[])
    return sz[k] - b * y[k]
}

define ode_z () {
    sx[k] = sin(cx[], x[])
    cx[k] = cos(sx[], x[])
    return sx[k] - b * z[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; b = $8
tsm($2, $3, $4)
EOF
