#!/bin/sh
# Wimol-Banlue system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc -l taylor.bc << EOF
define ode_x () {
    return y[k] - x[k]
}

define ode_y () {
    thx[k] = tanh(sh2x[], x[])
    sh2x[k] = sech2(thx[], x[])
    return - mul(z[], thx[])
}

define ode_z () {
    return mul(x[], y[]) + abs(y[]) - const(a)
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; a = $8
tsm($2, $3, $4)
EOF
