#!/bin/sh
# Rucklidge system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    return alpha * y[k] - kappa * x[k] - mul(y[], z[])
}

define ode_y () {
    return x[k]
}

define ode_z () {
    return sqr(y[]) - z[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; alpha = $8; kappa = $9
tsm($2, $3, $4)
EOF
