#!/bin/sh
# Rabinovich-Fabrikant system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    a[k] = z[k] + mul(x[], x[]) - const(1.0)
    return mul(y[], a[]) + gamma * x[k]
}

define ode_y () {
    b[k] = 4.0 * z[k] - a[k]
    return mul(x[], b[]) + gamma * y[k]
}

define ode_z () {
    c[k] = const(alpha) + mul(x[], y[])
    return - 2.0 * mul(z[], c[])
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; alpha = $8; gamma = $9
tsm($2, $3, $4)
EOF
