#!/bin/sh
# Genesio-Tesi system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    return y[k]
}

define ode_y () {
    return z[k]
}

define ode_z () {
    return - x[k] - mul(x[], x[]) - b * y[k] - a * z[k]
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; a = $8; b = $9
tsm($2, $3, $4)
EOF
