#!/bin/sh
# Halvorsen system
#  (c) 2018-2025 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file

. ./base.sh

BC_LINE_LENGTH=0 /usr/bin/bc taylor.bc << EOF
define ode_x () {
    return - a * x[k] - 4.0 * (y[k] + z[k]) - mul(y[], y[])
}

define ode_y () {
    return - a * y[k] - 4.0 * (z[k] + x[k]) - mul(z[], z[])
}

define ode_z () {
    return - a * z[k] - 4.0 * (x[k] + y[k]) - mul(x[], x[])
}

scale = $1; x[0] = $5; y[0] = $6; z[0] = $7; a = $8
tsm($2, $3, $4)
EOF
