#!/bin/sh
#
#  (c) 2018-2021 m4r35n357@gmail.com (Ian Smith), for licencing see the LICENCE file
#
# ./zig should be a symlink to your Zig executable
#
#  Example: ./zig-builds arm-linux-musleabihf ReleaseFast
#  Example: ./zig-builds aarch64-linux-musl ReleaseFast
#  Example: ./zig-builds x86_64-linux-musl ReleaseFast
#  Example: ./zig-builds i386-linux-musl ReleaseFast

target=$1
opt=$2

CCOPTS="-O $opt --single-threaded --strip --library c -target $target"

echo Zig version $(./zig version)

zig_build_exe="./zig build-exe -fno-lto"

for source in tsm-*.c
do
    $zig_build_exe $source taylor-ode.c main.c $CCOPTS
done

$zig_build_exe divergence.c $CCOPTS
$zig_build_exe taylor-test.c taylor-ode.c $CCOPTS
$zig_build_exe dual-test.c dual.c $CCOPTS

$zig_build_exe h-analysis.c symplectic.c $CCOPTS
$zig_build_exe h-kerr.c symplectic.c dual.c $CCOPTS
$zig_build_exe h-newton.c symplectic.c dual.c $CCOPTS
$zig_build_exe h-kerr-gen-particle.c dual.c $CCOPTS
$zig_build_exe h-kerr-gen-light.c $CCOPTS

ls -lh --color divergence* taylor-test dual-test tsm-* h-*

echo OK
